blank_issues_enabled: false
contact_links:
  - name: Quality Clouds Support
    url: https://qualityclouds.com
    about: For general product support, visit our site or email help@qualityclouds.com
    
